#ifndef _H_IOCONTROL_
#define _H_IOCONTROL_

#define		FILE_DEVICE_SHADOW_DRIVER	FILE_DEVICE_UNKNOWN

//IOCTL codes
#define		IOCTL_LOGIN					(ULONG) CTL_CODE(FILE_DEVICE_SHADOW_DRIVER, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define		IOCTL_LOGOUT				(ULONG) CTL_CODE(FILE_DEVICE_SHADOW_DRIVER, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define		IOCTL_HIDE_PROCESS			(ULONG) CTL_CODE(FILE_DEVICE_SHADOW_DRIVER, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif